spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/quiz_note_dev}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
  jackson:
    dateFormat: yyyy/MM/dd HH:mm:ss
    time-zone: Asia/Tokyo
  session:
    store-type: jdbc
    jdbc:
      table-name: t_session
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
  social:
    facebook:
      appId: ${QUIZ_NOTE_FACEBOOK_APP_ID:}
      appSecret: ${QUIZ_NOTE_FACEBOOK_APP_SECRET:}
      redirectUri: ${QUIZ_NOTE_FACEBOOK_REDIRECT_URL:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${QUIZ_NOTE_MAIL_ADDRESS:test}
    password: ${QUIZ_NOTE_MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 300

logging:
    config: classpath:config/logbak.xml

quiz:
  app-name: みんなのクイズ手帳
  url: https://www.quiz-note.com/
  cloud-host-url: ${QUIZ_NOTE_CLOUD_HOST_URL:https://cdn.quiz-note.com}
  s3-access-key: ${QUIZ_NOTE_S3_ACCESS_KEY:}
  s3-secret-key: ${QUIZ_NOTE_S3_SECRET_KEY:}
  s3-service-end-point: https://s3-ap-northeast-1.amazonaws.com
  s3-region: ap-northeast-1
  s3-bucket: ${QUIZ_NOTE_S3_BUCKET:quiz-note-dev}
  timeout: 21600
  slack-app-token: ${QUIZ_NOTE_SLACK_APP_TOKEN:}
  slack-contact-channel: contact
  aes-key: ${QUIZ_NOTE_AES_KEY:}
