spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/quiz_note_dev}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
  jackson:
    dateFormat: yyyy/MM/dd HH:mm:ss
    time-zone: Asia/Tokyo
  session:
    store-type: jdbc
    jdbc:
      table-name: t_session
