spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/quiz_note_dev}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
  jackson:
    dateFormat: yyyy/MM/dd HH:mm:ss
    time-zone: Asia/Tokyo
  session:
    store-type: jdbc
    jdbc:
      table-name: t_session

quiz:
  cloud-host-url: ${QUIZ_NOTE_CLOUD_HOST_URL:https://cdn.quiz-note.com}
  s3-access-key: ${QUIZ_NOTE_S3_ACCESS_KEY:}
  s3-secret-key: ${QUIZ_NOTE_S3_SECRET_KEY:}
  s3-service-end-point: https://s3-ap-northeast-1.amazonaws.com
  s3-region: ap-northeast-1
  s3-bucket: ${QUIZ_NOTE_S3_BUCKET:quiz-note-dev}
  timeout: 21600
