package com.api.note.quiz.domain;

import com.api.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_activity
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TActivityKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   アクティビティID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.activity_id
     *
     * @return the value of t_activity.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.activity_id
     *
     * @param activityId the value for t_activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
}