package com.api.note.quiz.domain;

import com.api.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_charge_log
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TChargeLogKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   課金ログID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_log.charge_log_id
     *
     * @mbg.generated
     */
    private Long chargeLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_log.charge_log_id
     *
     * @return the value of t_charge_log.charge_log_id
     *
     * @mbg.generated
     */
    public Long getChargeLogId() {
        return chargeLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_log.charge_log_id
     *
     * @param chargeLogId the value for t_charge_log.charge_log_id
     *
     * @mbg.generated
     */
    public void setChargeLogId(Long chargeLogId) {
        this.chargeLogId = chargeLogId;
    }
}