package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_charge_log
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TChargeLog extends TChargeLogKey implements Serializable {
    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_log.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   課金額
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_log.charge
     *
     * @mbg.generated
     */
    private Integer charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_log.account_id
     *
     * @return the value of t_charge_log.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_log.account_id
     *
     * @param accountId the value for t_charge_log.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_log.charge
     *
     * @return the value of t_charge_log.charge
     *
     * @mbg.generated
     */
    public Integer getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_log.charge
     *
     * @param charge the value for t_charge_log.charge
     *
     * @mbg.generated
     */
    public void setCharge(Integer charge) {
        this.charge = charge;
    }
}