package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_contact
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TContact extends TContactKey implements Serializable {
    /**
     * Database Column Remarks:
     *   既読フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact.read_flag
     *
     * @mbg.generated
     */
    private Boolean readFlag;

    /**
     * Database Column Remarks:
     *   名前
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contact
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact.read_flag
     *
     * @return the value of t_contact.read_flag
     *
     * @mbg.generated
     */
    public Boolean getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact.read_flag
     *
     * @param readFlag the value for t_contact.read_flag
     *
     * @mbg.generated
     */
    public void setReadFlag(Boolean readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact.name
     *
     * @return the value of t_contact.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact.name
     *
     * @param name the value for t_contact.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact.mail
     *
     * @return the value of t_contact.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact.mail
     *
     * @param mail the value for t_contact.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact.content
     *
     * @return the value of t_contact.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact.content
     *
     * @param content the value for t_contact.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}