package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_group_member
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TGroupMember extends TGroupMemberKey implements Serializable {
    /**
     * Database Column Remarks:
     *   グループID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_member.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_member.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   ブロックフラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_member.blocked
     *
     * @mbg.generated
     */
    private Boolean blocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_member.group_id
     *
     * @return the value of t_group_member.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_member.group_id
     *
     * @param groupId the value for t_group_member.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_member.account_id
     *
     * @return the value of t_group_member.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_member.account_id
     *
     * @param accountId the value for t_group_member.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_member.blocked
     *
     * @return the value of t_group_member.blocked
     *
     * @mbg.generated
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_member.blocked
     *
     * @param blocked the value for t_group_member.blocked
     *
     * @mbg.generated
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }
}