package com.api.note.quiz.domain;

import com.api.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_group_member
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TGroupMemberKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   グループメンバーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_member.group_member_id
     *
     * @mbg.generated
     */
    private Long groupMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_member.group_member_id
     *
     * @return the value of t_group_member.group_member_id
     *
     * @mbg.generated
     */
    public Long getGroupMemberId() {
        return groupMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_member.group_member_id
     *
     * @param groupMemberId the value for t_group_member.group_member_id
     *
     * @mbg.generated
     */
    public void setGroupMemberId(Long groupMemberId) {
        this.groupMemberId = groupMemberId;
    }
}