package com.api.note.quiz.domain;

import com.api.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quiz_tag
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TQuizTagKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   タグID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz_tag.quiz_tag_id
     *
     * @mbg.generated
     */
    private Long quizTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz_tag.quiz_tag_id
     *
     * @return the value of t_quiz_tag.quiz_tag_id
     *
     * @mbg.generated
     */
    public Long getQuizTagId() {
        return quizTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz_tag.quiz_tag_id
     *
     * @param quizTagId the value for t_quiz_tag.quiz_tag_id
     *
     * @mbg.generated
     */
    public void setQuizTagId(Long quizTagId) {
        this.quizTagId = quizTagId;
    }
}