package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quiz
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TQuiz extends TQuizKey implements Serializable {
    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   問題
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     * Database Column Remarks:
     *   答え
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * Database Column Remarks:
     *   ヒント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.hint
     *
     * @mbg.generated
     */
    private String hint;

    /**
     * Database Column Remarks:
     *   解説
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.explanation
     *
     * @mbg.generated
     */
    private String explanation;

    /**
     * Database Column Remarks:
     *   音声パス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.sound_url
     *
     * @mbg.generated
     */
    private String soundUrl;

    /**
     * Database Column Remarks:
     *   公開種別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.scope_type
     *
     * @mbg.generated
     */
    private String scopeType;

    /**
     * Database Column Remarks:
     *   いいね件数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.like_count
     *
     * @mbg.generated
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.account_id
     *
     * @return the value of t_quiz.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.account_id
     *
     * @param accountId the value for t_quiz.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.question
     *
     * @return the value of t_quiz.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.question
     *
     * @param question the value for t_quiz.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.answer
     *
     * @return the value of t_quiz.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.answer
     *
     * @param answer the value for t_quiz.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.hint
     *
     * @return the value of t_quiz.hint
     *
     * @mbg.generated
     */
    public String getHint() {
        return hint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.hint
     *
     * @param hint the value for t_quiz.hint
     *
     * @mbg.generated
     */
    public void setHint(String hint) {
        this.hint = hint == null ? null : hint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.explanation
     *
     * @return the value of t_quiz.explanation
     *
     * @mbg.generated
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.explanation
     *
     * @param explanation the value for t_quiz.explanation
     *
     * @mbg.generated
     */
    public void setExplanation(String explanation) {
        this.explanation = explanation == null ? null : explanation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.sound_url
     *
     * @return the value of t_quiz.sound_url
     *
     * @mbg.generated
     */
    public String getSoundUrl() {
        return soundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.sound_url
     *
     * @param soundUrl the value for t_quiz.sound_url
     *
     * @mbg.generated
     */
    public void setSoundUrl(String soundUrl) {
        this.soundUrl = soundUrl == null ? null : soundUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.scope_type
     *
     * @return the value of t_quiz.scope_type
     *
     * @mbg.generated
     */
    public String getScopeType() {
        return scopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.scope_type
     *
     * @param scopeType the value for t_quiz.scope_type
     *
     * @mbg.generated
     */
    public void setScopeType(String scopeType) {
        this.scopeType = scopeType == null ? null : scopeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.like_count
     *
     * @return the value of t_quiz.like_count
     *
     * @mbg.generated
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.like_count
     *
     * @param likeCount the value for t_quiz.like_count
     *
     * @mbg.generated
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}