package com.api.note.quiz.domain;

import com.api.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quiz
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TQuizKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   クイズID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz.quiz_id
     *
     * @mbg.generated
     */
    private Long quizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz.quiz_id
     *
     * @return the value of t_quiz.quiz_id
     *
     * @mbg.generated
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz.quiz_id
     *
     * @param quizId the value for t_quiz.quiz_id
     *
     * @mbg.generated
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }
}