package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quiz_tag
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TQuizTag extends TQuizTagKey implements Serializable {
    /**
     * Database Column Remarks:
     *   クイズID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz_tag.quiz_id
     *
     * @mbg.generated
     */
    private Long quizId;

    /**
     * Database Column Remarks:
     *   タグ名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quiz_tag.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz_tag.quiz_id
     *
     * @return the value of t_quiz_tag.quiz_id
     *
     * @mbg.generated
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz_tag.quiz_id
     *
     * @param quizId the value for t_quiz_tag.quiz_id
     *
     * @mbg.generated
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quiz_tag.name
     *
     * @return the value of t_quiz_tag.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quiz_tag.name
     *
     * @param name the value for t_quiz_tag.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}