package com.api.note.quiz.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_follow
 */
@EqualsAndHashCode
@ToString
public class VFollow implements Serializable {
    /**
     * Database Column Remarks:
     *   フォローID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_id
     *
     * @mbg.generated
     */
    private Long followId;

    /**
     * Database Column Remarks:
     *   ブロックフラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.block_flag
     *
     * @mbg.generated
     */
    private Boolean blockFlag;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_account_id
     *
     * @mbg.generated
     */
    private Integer followAccountId;

    /**
     * Database Column Remarks:
     *   フォローアカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follower_account_id
     *
     * @mbg.generated
     */
    private Integer followerAccountId;

    /**
     * Database Column Remarks:
     *   ログインID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_login_id
     *
     * @mbg.generated
     */
    private String followLoginId;

    /**
     * Database Column Remarks:
     *   アカウント名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_name
     *
     * @mbg.generated
     */
    private String followName;

    /**
     * Database Column Remarks:
     *   自己紹介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_description
     *
     * @mbg.generated
     */
    private String followDescription;

    /**
     * Database Column Remarks:
     *   画像パス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follow_img_url
     *
     * @mbg.generated
     */
    private String followImgUrl;

    /**
     * Database Column Remarks:
     *   ログインID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follower_login_id
     *
     * @mbg.generated
     */
    private String followerLoginId;

    /**
     * Database Column Remarks:
     *   アカウント名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follower_name
     *
     * @mbg.generated
     */
    private String followerName;

    /**
     * Database Column Remarks:
     *   自己紹介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follower_description
     *
     * @mbg.generated
     */
    private String followerDescription;

    /**
     * Database Column Remarks:
     *   画像パス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_follow.follower_img_url
     *
     * @mbg.generated
     */
    private String followerImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_id
     *
     * @return the value of v_follow.follow_id
     *
     * @mbg.generated
     */
    public Long getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_id
     *
     * @param followId the value for v_follow.follow_id
     *
     * @mbg.generated
     */
    public void setFollowId(Long followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.block_flag
     *
     * @return the value of v_follow.block_flag
     *
     * @mbg.generated
     */
    public Boolean getBlockFlag() {
        return blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.block_flag
     *
     * @param blockFlag the value for v_follow.block_flag
     *
     * @mbg.generated
     */
    public void setBlockFlag(Boolean blockFlag) {
        this.blockFlag = blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_account_id
     *
     * @return the value of v_follow.follow_account_id
     *
     * @mbg.generated
     */
    public Integer getFollowAccountId() {
        return followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_account_id
     *
     * @param followAccountId the value for v_follow.follow_account_id
     *
     * @mbg.generated
     */
    public void setFollowAccountId(Integer followAccountId) {
        this.followAccountId = followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follower_account_id
     *
     * @return the value of v_follow.follower_account_id
     *
     * @mbg.generated
     */
    public Integer getFollowerAccountId() {
        return followerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follower_account_id
     *
     * @param followerAccountId the value for v_follow.follower_account_id
     *
     * @mbg.generated
     */
    public void setFollowerAccountId(Integer followerAccountId) {
        this.followerAccountId = followerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_login_id
     *
     * @return the value of v_follow.follow_login_id
     *
     * @mbg.generated
     */
    public String getFollowLoginId() {
        return followLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_login_id
     *
     * @param followLoginId the value for v_follow.follow_login_id
     *
     * @mbg.generated
     */
    public void setFollowLoginId(String followLoginId) {
        this.followLoginId = followLoginId == null ? null : followLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_name
     *
     * @return the value of v_follow.follow_name
     *
     * @mbg.generated
     */
    public String getFollowName() {
        return followName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_name
     *
     * @param followName the value for v_follow.follow_name
     *
     * @mbg.generated
     */
    public void setFollowName(String followName) {
        this.followName = followName == null ? null : followName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_description
     *
     * @return the value of v_follow.follow_description
     *
     * @mbg.generated
     */
    public String getFollowDescription() {
        return followDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_description
     *
     * @param followDescription the value for v_follow.follow_description
     *
     * @mbg.generated
     */
    public void setFollowDescription(String followDescription) {
        this.followDescription = followDescription == null ? null : followDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follow_img_url
     *
     * @return the value of v_follow.follow_img_url
     *
     * @mbg.generated
     */
    public String getFollowImgUrl() {
        return followImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follow_img_url
     *
     * @param followImgUrl the value for v_follow.follow_img_url
     *
     * @mbg.generated
     */
    public void setFollowImgUrl(String followImgUrl) {
        this.followImgUrl = followImgUrl == null ? null : followImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follower_login_id
     *
     * @return the value of v_follow.follower_login_id
     *
     * @mbg.generated
     */
    public String getFollowerLoginId() {
        return followerLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follower_login_id
     *
     * @param followerLoginId the value for v_follow.follower_login_id
     *
     * @mbg.generated
     */
    public void setFollowerLoginId(String followerLoginId) {
        this.followerLoginId = followerLoginId == null ? null : followerLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follower_name
     *
     * @return the value of v_follow.follower_name
     *
     * @mbg.generated
     */
    public String getFollowerName() {
        return followerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follower_name
     *
     * @param followerName the value for v_follow.follower_name
     *
     * @mbg.generated
     */
    public void setFollowerName(String followerName) {
        this.followerName = followerName == null ? null : followerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follower_description
     *
     * @return the value of v_follow.follower_description
     *
     * @mbg.generated
     */
    public String getFollowerDescription() {
        return followerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follower_description
     *
     * @param followerDescription the value for v_follow.follower_description
     *
     * @mbg.generated
     */
    public void setFollowerDescription(String followerDescription) {
        this.followerDescription = followerDescription == null ? null : followerDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_follow.follower_img_url
     *
     * @return the value of v_follow.follower_img_url
     *
     * @mbg.generated
     */
    public String getFollowerImgUrl() {
        return followerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_follow.follower_img_url
     *
     * @param followerImgUrl the value for v_follow.follower_img_url
     *
     * @mbg.generated
     */
    public void setFollowerImgUrl(String followerImgUrl) {
        this.followerImgUrl = followerImgUrl == null ? null : followerImgUrl.trim();
    }
}