package com.api.note.quiz.domain;

import com.api.common.business.domain.BaseExample;
import java.util.ArrayList;
import java.util.List;

public class VFollowExample implements BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected Integer limitClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected Integer offsetClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public VFollowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void setLimitClause(Integer limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public Integer getLimitClause() {
        return limitClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public void setOffsetClause(Integer offsetClause) {
        this.offsetClause = offsetClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public Integer getOffsetClause() {
        return offsetClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFollowIdIsNull() {
            addCriterion("follow_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowIdIsNotNull() {
            addCriterion("follow_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowIdEqualTo(Long value) {
            addCriterion("follow_id =", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotEqualTo(Long value) {
            addCriterion("follow_id <>", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdGreaterThan(Long value) {
            addCriterion("follow_id >", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdGreaterThanOrEqualTo(Long value) {
            addCriterion("follow_id >=", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdLessThan(Long value) {
            addCriterion("follow_id <", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdLessThanOrEqualTo(Long value) {
            addCriterion("follow_id <=", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdIn(List<Long> values) {
            addCriterion("follow_id in", values, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotIn(List<Long> values) {
            addCriterion("follow_id not in", values, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdBetween(Long value1, Long value2) {
            addCriterion("follow_id between", value1, value2, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotBetween(Long value1, Long value2) {
            addCriterion("follow_id not between", value1, value2, "followId");
            return (Criteria) this;
        }

        public Criteria andBlockFlagIsNull() {
            addCriterion("block_flag is null");
            return (Criteria) this;
        }

        public Criteria andBlockFlagIsNotNull() {
            addCriterion("block_flag is not null");
            return (Criteria) this;
        }

        public Criteria andBlockFlagEqualTo(Boolean value) {
            addCriterion("block_flag =", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagNotEqualTo(Boolean value) {
            addCriterion("block_flag <>", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagGreaterThan(Boolean value) {
            addCriterion("block_flag >", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("block_flag >=", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagLessThan(Boolean value) {
            addCriterion("block_flag <", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("block_flag <=", value, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagIn(List<Boolean> values) {
            addCriterion("block_flag in", values, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagNotIn(List<Boolean> values) {
            addCriterion("block_flag not in", values, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("block_flag between", value1, value2, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andBlockFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("block_flag not between", value1, value2, "blockFlag");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdIsNull() {
            addCriterion("follow_account_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdIsNotNull() {
            addCriterion("follow_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdEqualTo(Integer value) {
            addCriterion("follow_account_id =", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdNotEqualTo(Integer value) {
            addCriterion("follow_account_id <>", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdGreaterThan(Integer value) {
            addCriterion("follow_account_id >", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("follow_account_id >=", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdLessThan(Integer value) {
            addCriterion("follow_account_id <", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("follow_account_id <=", value, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdIn(List<Integer> values) {
            addCriterion("follow_account_id in", values, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdNotIn(List<Integer> values) {
            addCriterion("follow_account_id not in", values, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("follow_account_id between", value1, value2, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("follow_account_id not between", value1, value2, "followAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdIsNull() {
            addCriterion("follower_account_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdIsNotNull() {
            addCriterion("follower_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdEqualTo(Integer value) {
            addCriterion("follower_account_id =", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdNotEqualTo(Integer value) {
            addCriterion("follower_account_id <>", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdGreaterThan(Integer value) {
            addCriterion("follower_account_id >", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("follower_account_id >=", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdLessThan(Integer value) {
            addCriterion("follower_account_id <", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("follower_account_id <=", value, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdIn(List<Integer> values) {
            addCriterion("follower_account_id in", values, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdNotIn(List<Integer> values) {
            addCriterion("follower_account_id not in", values, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("follower_account_id between", value1, value2, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowerAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("follower_account_id not between", value1, value2, "followerAccountId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdIsNull() {
            addCriterion("follow_login_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdIsNotNull() {
            addCriterion("follow_login_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdEqualTo(String value) {
            addCriterion("follow_login_id =", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdNotEqualTo(String value) {
            addCriterion("follow_login_id <>", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdGreaterThan(String value) {
            addCriterion("follow_login_id >", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("follow_login_id >=", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdLessThan(String value) {
            addCriterion("follow_login_id <", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdLessThanOrEqualTo(String value) {
            addCriterion("follow_login_id <=", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdLike(String value) {
            addCriterion("follow_login_id like", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdNotLike(String value) {
            addCriterion("follow_login_id not like", value, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdIn(List<String> values) {
            addCriterion("follow_login_id in", values, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdNotIn(List<String> values) {
            addCriterion("follow_login_id not in", values, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdBetween(String value1, String value2) {
            addCriterion("follow_login_id between", value1, value2, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdNotBetween(String value1, String value2) {
            addCriterion("follow_login_id not between", value1, value2, "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowNameIsNull() {
            addCriterion("follow_name is null");
            return (Criteria) this;
        }

        public Criteria andFollowNameIsNotNull() {
            addCriterion("follow_name is not null");
            return (Criteria) this;
        }

        public Criteria andFollowNameEqualTo(String value) {
            addCriterion("follow_name =", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameNotEqualTo(String value) {
            addCriterion("follow_name <>", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameGreaterThan(String value) {
            addCriterion("follow_name >", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameGreaterThanOrEqualTo(String value) {
            addCriterion("follow_name >=", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameLessThan(String value) {
            addCriterion("follow_name <", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameLessThanOrEqualTo(String value) {
            addCriterion("follow_name <=", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameLike(String value) {
            addCriterion("follow_name like", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameNotLike(String value) {
            addCriterion("follow_name not like", value, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameIn(List<String> values) {
            addCriterion("follow_name in", values, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameNotIn(List<String> values) {
            addCriterion("follow_name not in", values, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameBetween(String value1, String value2) {
            addCriterion("follow_name between", value1, value2, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowNameNotBetween(String value1, String value2) {
            addCriterion("follow_name not between", value1, value2, "followName");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionIsNull() {
            addCriterion("follow_description is null");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionIsNotNull() {
            addCriterion("follow_description is not null");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionEqualTo(String value) {
            addCriterion("follow_description =", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionNotEqualTo(String value) {
            addCriterion("follow_description <>", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionGreaterThan(String value) {
            addCriterion("follow_description >", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("follow_description >=", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionLessThan(String value) {
            addCriterion("follow_description <", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionLessThanOrEqualTo(String value) {
            addCriterion("follow_description <=", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionLike(String value) {
            addCriterion("follow_description like", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionNotLike(String value) {
            addCriterion("follow_description not like", value, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionIn(List<String> values) {
            addCriterion("follow_description in", values, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionNotIn(List<String> values) {
            addCriterion("follow_description not in", values, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionBetween(String value1, String value2) {
            addCriterion("follow_description between", value1, value2, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionNotBetween(String value1, String value2) {
            addCriterion("follow_description not between", value1, value2, "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlIsNull() {
            addCriterion("follow_img_url is null");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlIsNotNull() {
            addCriterion("follow_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlEqualTo(String value) {
            addCriterion("follow_img_url =", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlNotEqualTo(String value) {
            addCriterion("follow_img_url <>", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlGreaterThan(String value) {
            addCriterion("follow_img_url >", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("follow_img_url >=", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlLessThan(String value) {
            addCriterion("follow_img_url <", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlLessThanOrEqualTo(String value) {
            addCriterion("follow_img_url <=", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlLike(String value) {
            addCriterion("follow_img_url like", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlNotLike(String value) {
            addCriterion("follow_img_url not like", value, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlIn(List<String> values) {
            addCriterion("follow_img_url in", values, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlNotIn(List<String> values) {
            addCriterion("follow_img_url not in", values, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlBetween(String value1, String value2) {
            addCriterion("follow_img_url between", value1, value2, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlNotBetween(String value1, String value2) {
            addCriterion("follow_img_url not between", value1, value2, "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdIsNull() {
            addCriterion("follower_login_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdIsNotNull() {
            addCriterion("follower_login_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdEqualTo(String value) {
            addCriterion("follower_login_id =", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdNotEqualTo(String value) {
            addCriterion("follower_login_id <>", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdGreaterThan(String value) {
            addCriterion("follower_login_id >", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("follower_login_id >=", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdLessThan(String value) {
            addCriterion("follower_login_id <", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdLessThanOrEqualTo(String value) {
            addCriterion("follower_login_id <=", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdLike(String value) {
            addCriterion("follower_login_id like", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdNotLike(String value) {
            addCriterion("follower_login_id not like", value, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdIn(List<String> values) {
            addCriterion("follower_login_id in", values, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdNotIn(List<String> values) {
            addCriterion("follower_login_id not in", values, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdBetween(String value1, String value2) {
            addCriterion("follower_login_id between", value1, value2, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdNotBetween(String value1, String value2) {
            addCriterion("follower_login_id not between", value1, value2, "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerNameIsNull() {
            addCriterion("follower_name is null");
            return (Criteria) this;
        }

        public Criteria andFollowerNameIsNotNull() {
            addCriterion("follower_name is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerNameEqualTo(String value) {
            addCriterion("follower_name =", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameNotEqualTo(String value) {
            addCriterion("follower_name <>", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameGreaterThan(String value) {
            addCriterion("follower_name >", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameGreaterThanOrEqualTo(String value) {
            addCriterion("follower_name >=", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameLessThan(String value) {
            addCriterion("follower_name <", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameLessThanOrEqualTo(String value) {
            addCriterion("follower_name <=", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameLike(String value) {
            addCriterion("follower_name like", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameNotLike(String value) {
            addCriterion("follower_name not like", value, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameIn(List<String> values) {
            addCriterion("follower_name in", values, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameNotIn(List<String> values) {
            addCriterion("follower_name not in", values, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameBetween(String value1, String value2) {
            addCriterion("follower_name between", value1, value2, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerNameNotBetween(String value1, String value2) {
            addCriterion("follower_name not between", value1, value2, "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionIsNull() {
            addCriterion("follower_description is null");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionIsNotNull() {
            addCriterion("follower_description is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionEqualTo(String value) {
            addCriterion("follower_description =", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionNotEqualTo(String value) {
            addCriterion("follower_description <>", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionGreaterThan(String value) {
            addCriterion("follower_description >", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("follower_description >=", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionLessThan(String value) {
            addCriterion("follower_description <", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionLessThanOrEqualTo(String value) {
            addCriterion("follower_description <=", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionLike(String value) {
            addCriterion("follower_description like", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionNotLike(String value) {
            addCriterion("follower_description not like", value, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionIn(List<String> values) {
            addCriterion("follower_description in", values, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionNotIn(List<String> values) {
            addCriterion("follower_description not in", values, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionBetween(String value1, String value2) {
            addCriterion("follower_description between", value1, value2, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionNotBetween(String value1, String value2) {
            addCriterion("follower_description not between", value1, value2, "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlIsNull() {
            addCriterion("follower_img_url is null");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlIsNotNull() {
            addCriterion("follower_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlEqualTo(String value) {
            addCriterion("follower_img_url =", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlNotEqualTo(String value) {
            addCriterion("follower_img_url <>", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlGreaterThan(String value) {
            addCriterion("follower_img_url >", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("follower_img_url >=", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlLessThan(String value) {
            addCriterion("follower_img_url <", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlLessThanOrEqualTo(String value) {
            addCriterion("follower_img_url <=", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlLike(String value) {
            addCriterion("follower_img_url like", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlNotLike(String value) {
            addCriterion("follower_img_url not like", value, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlIn(List<String> values) {
            addCriterion("follower_img_url in", values, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlNotIn(List<String> values) {
            addCriterion("follower_img_url not in", values, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlBetween(String value1, String value2) {
            addCriterion("follower_img_url between", value1, value2, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlNotBetween(String value1, String value2) {
            addCriterion("follower_img_url not between", value1, value2, "followerImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowLoginIdLikeInsensitive(String value) {
            addCriterion("upper(follow_login_id) like", value.toUpperCase(), "followLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowNameLikeInsensitive(String value) {
            addCriterion("upper(follow_name) like", value.toUpperCase(), "followName");
            return (Criteria) this;
        }

        public Criteria andFollowDescriptionLikeInsensitive(String value) {
            addCriterion("upper(follow_description) like", value.toUpperCase(), "followDescription");
            return (Criteria) this;
        }

        public Criteria andFollowImgUrlLikeInsensitive(String value) {
            addCriterion("upper(follow_img_url) like", value.toUpperCase(), "followImgUrl");
            return (Criteria) this;
        }

        public Criteria andFollowerLoginIdLikeInsensitive(String value) {
            addCriterion("upper(follower_login_id) like", value.toUpperCase(), "followerLoginId");
            return (Criteria) this;
        }

        public Criteria andFollowerNameLikeInsensitive(String value) {
            addCriterion("upper(follower_name) like", value.toUpperCase(), "followerName");
            return (Criteria) this;
        }

        public Criteria andFollowerDescriptionLikeInsensitive(String value) {
            addCriterion("upper(follower_description) like", value.toUpperCase(), "followerDescription");
            return (Criteria) this;
        }

        public Criteria andFollowerImgUrlLikeInsensitive(String value) {
            addCriterion("upper(follower_img_url) like", value.toUpperCase(), "followerImgUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_follow
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_follow
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}